name: Build on branches

on:
  push:
    branches:
      - master
      - deploy
jobs:

  branches:
    name: Build on branches
    runs-on: ubuntu-20.04
    env:
      GO_VERSION: 1.19
      GOLANGCI_LINT_VERSION: v1.49.0

    steps:

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ env.GO_VERSION }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      # https://github.com/marketplace/actions/checkout
      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-hub-agent-traefik-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hub-agent-traefik-go-

      - name: Check and get dependencies
        run: |
          go mod download
          go mod tidy
          git diff --exit-code go.mod
          git diff --exit-code go.sum

      # https://golangci-lint.run/usage/install#other-ci
      - name: Install golangci-lint ${{ env.GOLANGCI_LINT_VERSION }}
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin ${GOLANGCI_LINT_VERSION}

      - name: Make
        run: make

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Login to GHCR
        if: github.repository == 'traefik/hub-agent-traefik'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: traefiker
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build multi arch experimental image
        if: github.repository == 'traefik/hub-agent-traefik' && github.ref == 'refs/heads/master'
        env:
          DOCKER_BUILDX_ARGS: --push
        run: |
          make multi-arch-image-experimental
          make multi-arch-image-${GITHUB_REF_NAME}-${GITHUB_SHA:0:7}-$(date +%s)
